/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LidsCard {
    }
    interface LidsIcon {
        "height": string;
        "name": string;
        "width": string;
    }
    interface LidsMasthead {
    }
    interface LidsOption {
        "selected": boolean;
        "value": string;
    }
    interface LidsSearchbar {
        /**
          * The placeholder to use for the input field.
          * @type {string}
          * @memberof Searchbar
         */
        "placeholder": string;
    }
    interface LidsSelect {
        /**
          * The current value of the element.
          * @type {string}
          * @memberof Select
         */
        "value": string;
    }
}
declare global {
    interface HTMLLidsCardElement extends Components.LidsCard, HTMLStencilElement {
    }
    var HTMLLidsCardElement: {
        prototype: HTMLLidsCardElement;
        new (): HTMLLidsCardElement;
    };
    interface HTMLLidsIconElement extends Components.LidsIcon, HTMLStencilElement {
    }
    var HTMLLidsIconElement: {
        prototype: HTMLLidsIconElement;
        new (): HTMLLidsIconElement;
    };
    interface HTMLLidsMastheadElement extends Components.LidsMasthead, HTMLStencilElement {
    }
    var HTMLLidsMastheadElement: {
        prototype: HTMLLidsMastheadElement;
        new (): HTMLLidsMastheadElement;
    };
    interface HTMLLidsOptionElement extends Components.LidsOption, HTMLStencilElement {
    }
    var HTMLLidsOptionElement: {
        prototype: HTMLLidsOptionElement;
        new (): HTMLLidsOptionElement;
    };
    interface HTMLLidsSearchbarElement extends Components.LidsSearchbar, HTMLStencilElement {
    }
    var HTMLLidsSearchbarElement: {
        prototype: HTMLLidsSearchbarElement;
        new (): HTMLLidsSearchbarElement;
    };
    interface HTMLLidsSelectElement extends Components.LidsSelect, HTMLStencilElement {
    }
    var HTMLLidsSelectElement: {
        prototype: HTMLLidsSelectElement;
        new (): HTMLLidsSelectElement;
    };
    interface HTMLElementTagNameMap {
        "lids-card": HTMLLidsCardElement;
        "lids-icon": HTMLLidsIconElement;
        "lids-masthead": HTMLLidsMastheadElement;
        "lids-option": HTMLLidsOptionElement;
        "lids-searchbar": HTMLLidsSearchbarElement;
        "lids-select": HTMLLidsSelectElement;
    }
}
declare namespace LocalJSX {
    interface LidsCard {
    }
    interface LidsIcon {
        "height"?: string;
        "name"?: string;
        "width"?: string;
    }
    interface LidsMasthead {
    }
    interface LidsOption {
        "selected"?: boolean;
        "value"?: string;
    }
    interface LidsSearchbar {
        /**
          * Custom event dispatching the value of the input on submission.
          * @type {EventEmitter<string>}
          * @memberof Searchbar
         */
        "onOnsubmit"?: (event: CustomEvent<string>) => void;
        /**
          * The placeholder to use for the input field.
          * @type {string}
          * @memberof Searchbar
         */
        "placeholder"?: string;
    }
    interface LidsSelect {
        /**
          * Custom event dispatching the value of the select on submission.
          * @type {EventEmitter<string>}
          * @memberof Select
         */
        "onOnchange"?: (event: CustomEvent<string>) => void;
        /**
          * The current value of the element.
          * @type {string}
          * @memberof Select
         */
        "value"?: string;
    }
    interface IntrinsicElements {
        "lids-card": LidsCard;
        "lids-icon": LidsIcon;
        "lids-masthead": LidsMasthead;
        "lids-option": LidsOption;
        "lids-searchbar": LidsSearchbar;
        "lids-select": LidsSelect;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "lids-card": LocalJSX.LidsCard & JSXBase.HTMLAttributes<HTMLLidsCardElement>;
            "lids-icon": LocalJSX.LidsIcon & JSXBase.HTMLAttributes<HTMLLidsIconElement>;
            "lids-masthead": LocalJSX.LidsMasthead & JSXBase.HTMLAttributes<HTMLLidsMastheadElement>;
            "lids-option": LocalJSX.LidsOption & JSXBase.HTMLAttributes<HTMLLidsOptionElement>;
            "lids-searchbar": LocalJSX.LidsSearchbar & JSXBase.HTMLAttributes<HTMLLidsSearchbarElement>;
            "lids-select": LocalJSX.LidsSelect & JSXBase.HTMLAttributes<HTMLLidsSelectElement>;
        }
    }
}
