name: Deploy

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          persist-credentials: false
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: |
          npm install
          npm run build

      - name: Prebuild
        run: npm run storybook.prebuild

      - name: Build
        run: npm run storybook.build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: .storybook/dist # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
