name: Validation

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: npm install

      - name: Commit Convention Check
        run: git log -1 --pretty=format:"%s" | npx commitlint

      - name: Lint
        run: npm run lint

      - name: Icons Build
        run: npm run build.icons

      - name: Test
        run: npm run test
